language: php
os:
  - linux

php:
  - 7.0
  - nightly

install: composer install

after_script:
  - vendor/bin/test-reporter

addons:
  code_climate:
    repo_token: e7fe54cf0e2cbf1c51df149b7f2911c812751f9154fe0ac797e38fb610eb00b4
