#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use cedrichaase\DotGen\Console\Application;
use cedrichaase\DotGen\Console\Command\RenderCommand;

$app = new Application();
$app->add(new RenderCommand());
$app->run();